CLASSES = Valeur.java Couleur.java Carte.java Tas.java Bataille.java Test.java PileDeCartes.java Joueur.java
PROG = Test

compile:

	javac ${CLASSES}
		
exec:

	java ${PROG}

cleanobj:

	rm *.class
		
all:compile exec
