/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GENERATEUR_H_RPCGEN
#define _GENERATEUR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct nvg {
	int tab[2500];
	int m;
	int n;
};
typedef struct nvg nvg;

struct histogr {
	int tab[255];
};
typedef struct histogr histogr;

#define TP6 0x30000021
#define HISTOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HISTO 1
extern  histogr * histo_1(nvg *, CLIENT *);
extern  histogr * histo_1_svc(nvg *, struct svc_req *);
#define MOY 2
extern  nvg * moy_1(nvg *, CLIENT *);
extern  nvg * moy_1_svc(nvg *, struct svc_req *);
#define MED 3
extern  nvg * med_1(nvg *, CLIENT *);
extern  nvg * med_1_svc(nvg *, struct svc_req *);
extern int tp6_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HISTO 1
extern  histogr * histo_1();
extern  histogr * histo_1_svc();
#define MOY 2
extern  nvg * moy_1();
extern  nvg * moy_1_svc();
#define MED 3
extern  nvg * med_1();
extern  nvg * med_1_svc();
extern int tp6_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nvg (XDR *, nvg*);
extern  bool_t xdr_histogr (XDR *, histogr*);

#else /* K&R C */
extern bool_t xdr_nvg ();
extern bool_t xdr_histogr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GENERATEUR_H_RPCGEN */
