/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXO1_H_RPCGEN
#define _EXO1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_1_argument {
	int arg1;
	int arg2;
};
typedef struct add_1_argument add_1_argument;

struct mult_1_argument {
	int arg1;
	int arg2;
};
typedef struct mult_1_argument mult_1_argument;

#define EXO1 0x30000020
#define EXO1VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(int , int , CLIENT *);
extern  int * add_1_svc(int , int , struct svc_req *);
#define MULT 2
extern  int * mult_1(int , int , CLIENT *);
extern  int * mult_1_svc(int , int , struct svc_req *);
extern int exo1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define MULT 2
extern  int * mult_1();
extern  int * mult_1_svc();
extern int exo1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_1_argument (XDR *, add_1_argument*);
extern  bool_t xdr_mult_1_argument (XDR *, mult_1_argument*);

#else /* K&R C */
extern bool_t xdr_add_1_argument ();
extern bool_t xdr_mult_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXO1_H_RPCGEN */
