/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "generateur.h"
#include <time.h>
#include <unistd.h>

void vider_stdin(){

    int c;
 
    do {
        c = getchar();
    } while (c != '\n' && c != EOF);
}

void remplir_image(struct nvg *i){

	int j;
	int l, h;
	
	do{
		printf("\nVeuillez entrer la hauteur de l'image (max. 50) : ");
		scanf("%i", &h);
	}while(h>50 || h<0);
	
	do{
		printf("Veuillez entrer la largeur de l'image (max. 50) : ");
		scanf("%i", &l);
	}while(l>50 || l<0);
	
	for(j=0; j<(l*h); j++){	
		i->tab[j] = rand()%256;	
	}
	
	i->m = h;
	i->n = l;
}

void afficher_image(nvg *image){

	int i,j;
	
	printf("\n");
	
	for(i=0; i < (image->m); i++){
	
		for(j=0; j < (image->n); j++){
		
			printf("%i\t", image->tab[(i*(image->n)) +j]);
		}
		
		printf("\n");
	}
	
	printf("\n\nLongueur : %i\nHauteur : %i\n\n", image->n, image->m);
}

//Affiche un histogramme
void afficher_histo(histogr *h){

	int i;
	
	printf("Affichage de l'histogramme : \n\n");
	
	for(i=0; i<255; i++){
	
		if(!(i%10)){
		
			printf("\n");
		}
		
		printf("%i ", h->tab[i]);
	}
	
	printf("\n");
}

void
tp6_1(char *host)
{
	CLIENT *clnt;
	
	histogr  *histogramme;
	nvg  *image_retour;
	nvg image;
	
	char choix;

#ifndef	DEBUG
	clnt = clnt_create (host, TP6, HISTOVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	srand(getpid());
	
	while(1){
	
		printf("Options :\n\n\t1.Déterminer l'histogramme de votre image\n\t2.Appliquer un filtre moyenne sur votre image\n\t3.Appliquer un filtre médian sur votre image\n\nVotre choix (q pour quitter) : ");
	
		scanf("%c", &choix);
		vider_stdin();
		
		if(choix != 'q'){
			remplir_image(&image);
			afficher_image(&image);
			vider_stdin();
		}
		
		switch(choix){
	
			case '1':	histogramme = histo_1(&image, clnt);
						if (histogramme == (histogr *) NULL) {
							clnt_perror (clnt, "call failed");
						}
						else{
						
							afficher_histo(histogramme);
						}
						break;
		
			case '2':	image_retour = moy_1(&image, clnt);
						if (image_retour == (nvg *) NULL) {
							clnt_perror (clnt, "call failed");
						}
						else{
						
							printf("\t\t*****************Image de résultat******************");
							afficher_image(image_retour);
						}	
						break;
					
			case '3':	image_retour = med_1(&image, clnt);
						if (image_retour == (nvg *) NULL) {
							clnt_perror (clnt, "call failed");
						}
						else{
							afficher_image(image_retour);
						}		
						break;
						
			case 'q':	printf("\n\nFin du programme\n");
						exit (0);
		}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tp6_1 (host);
	exit (0);
}
