/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "generateur.h"

//Fonction utilisée dans qsort pour trier un tableau
int cmp_int(const void *a, const void *b){

	int *c = (int *)a;
	int *d = (int *)b;
	
	return *c-*d;
}

//Recopie les bords d'une matrice sur une autre
void recopier_bords(nvg *image, nvg *image_res){

	int i, j;
	
	for(i=0; i < (image->m); i++){
		image_res->tab[i*(image->n)] = image->tab[i*(image->n)];
		image_res->tab[(i+1)*(image->n) - 1] = image->tab[(i+1)*(image->n) - 1];
	}
	
	for(j=0; j < (image->n); j++){
	
		image_res->tab[j] = image->tab[j];
		image_res->tab[(image->n)*(image->m - 1)+j] = image->tab[(image->n)*(image->m - 1)+j];
	}
}

//Affiche une image (pour DEBUG)
void afficher_image(nvg *image){

	int i,j;
	
	printf("\n");
	
	for(i=0; i< (image->m); i++){
	
		for(j=0; j< (image->n); j++){
		
			printf("%i\t", image->tab[(i*(image->n)) +j]);
		}
		
		printf("\n");
	}
	
	printf("\n\nLongueur : %i\nHauteur : %i\n\n", image->m, image->n);
}

//Calcule la moyenne d'une matrice 3*3
int moyenne_matrice_33(int *mat){
	
	int moyenne = 0, i;
	
	for(i=0; i<10; i++){
	
		moyenne += mat[i];
	}
	
	return (moyenne/9);
}

//Retourne le médian d'une matrice 3*3
int median_matrice_33(int *mat){
	
	//Triage du tableau
	qsort(mat, 9, sizeof(int), cmp_int);
	
	//Retour de la valeur médiane
	return(mat[4]);
}

//Rempli une matrice 3*3 à l'aide d'une image nvg et d'un indice de cette image
void remplir_matrice_33(nvg *image, int i, int *matrice){

	int x,y;
	
	for(x = (i-1), y = 0; x <= (i+1); x++, y++){
	
		matrice[y] = image->tab[x];
	}
	
	for(x = ((i-1) - (image->n)); x <= ((i+1) - (image->n)); x++, y++){
	
		matrice[y] = image->tab[x];
	}
	
	for(x = ((i-1) + (image->n)); x <= ((i+1) + (image->n)); x++, y++){
	
		matrice[y] = image->tab[x];
	}
}

//Renvoi l'histogramme d'une image
histogr *
histo_1_svc(nvg *image,  struct svc_req *rqstp)
{
	static histogr  histo;
	int i, j;
	
	printf("\n\nAppel de la fonction histogramme en RPC\n");
	
	for(i=0; i<255; i++){
	
		histo.tab[i] = 0;
	}
	
	for(i=0; i<(image->n); i++){
	
		for(j=0; j<(image->m); j++){
		
			histo.tab[image->tab[(i*(image->n)+j)]] += 1;
		}
	}

	printf("Retour des résultats\n");
	
	return &histo;
}

//Renvoi une image à laquelle on a appliqué un filtre moyenne
nvg *
moy_1_svc(nvg *image,  struct svc_req *rqstp)
{
	static nvg image_res;
	
	printf("\n\nAppel de la fonction moyenne en RPC\n");
	
	int matrice33[9], i, j;
	
	image_res.m = image->m;
	image_res.n = image->n;
	
	//On recopie les bords de l'image
	recopier_bords(image, &image_res);
	
	//On applique le filtre
	for(i=1; i < ((image->m) - 1); i++){
	
		for(j=1; j < ((image->n) - 1); j++){
		
			remplir_matrice_33(image, i*(image->n) + j, matrice33);
			image_res.tab[i*(image->n) + j] = moyenne_matrice_33(matrice33);
		}
	}
	
	printf("Retour des résultats");
	
	return &image_res;
}

//Renvoi une image à laquelle on a appliqué un filtre médian
nvg *
med_1_svc(nvg *image,  struct svc_req *rqstp)
{
	static nvg image_res;
	
	printf("\n\nAppel de la fonction médian en RPC\n");
	
	int matrice33[9], i, j;
	
	image_res.m = image->m;
	image_res.n = image->n;
	
	//On recopie les bords de l'image
	recopier_bords(image, &image_res);
	
	//On applique le filtre
	for(i=1; i < ((image->m) - 1); i++){
	
		for(j=1; j < ((image->n) - 1); j++){
		
			remplir_matrice_33(image, i*(image->n) + j, matrice33);
			image_res.tab[i*(image->n) + j] = median_matrice_33(matrice33);
		}
	}
	
	printf("Retour des résultats");
	
	return &image_res;
}
