/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exo1.h"

void vider_stdin(){

    int c;
 
    do {
        c = getchar();
    } while (c != '\n' && c != EOF);
}

void
exo1_1(char *host)
{
	CLIENT *clnt;
	int  *resultat;
	int argument1, argument2;
	
	char choix;

#ifndef	DEBUG
	clnt = clnt_create (host, EXO1, EXO1VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	while(1){
	
		printf("Options :\n\n\t1.Additionner 2 nombres\n\t2.Multiplier deux nombres\n\nVotre choix (q pour quitter) : ");
	
		scanf("%c", &choix);
		vider_stdin();

		if(choix != 'q'){
		
			printf("\nEntrez l'argument 1 : ");
			scanf("%i", &argument1);

			printf("Entrez l'argument 2 : ");
			scanf("%i", &argument2);
		}
		
		vider_stdin();
				
		switch(choix){
	
			case '1':	resultat = add_1(argument1, argument2, clnt);
						if (resultat == (int *) NULL) {
							clnt_perror (clnt, "call failed");
						}
						else{
						
							printf("\nRésultat : %i\n", *resultat);
						}
						break;
		
			case '2':	resultat = mult_1(argument1, argument2, clnt);
						if (resultat == (int *) NULL) {
							clnt_perror (clnt, "call failed");
						}
						else{
						
							printf("\nRésultat : %i\n", *resultat);
						}
						break;
					
			case 'q':	printf("Fin du programme\n");
						exit(0);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	exo1_1 (host);
exit (0);
}
