/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exo1.h"

int *
add_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 + arg2;

	return &result;
}

int *
mult_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 * arg2;

	return &result;
}
