CLASSES = Texte.java CompteurOccurencesCar.java CompteurOccurences.java Test.java
PROG = Test

compile:

	javac ${CLASSES}
		
exec:

	java ${PROG}

cleanobj:

	rm *.class
		
test:compile exec cleanobj
